# Generated by Django 4.2.2 on 2024-12-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_roomcategory_name_alter_roomcategory_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomCategory',
        ),
    ]
