# Generated by Django 4.2.17 on 2024-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_category_delete_roomcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='category',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
