# Generated by Django 4.2.17 on 2024-12-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_event_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
