# Generated by Django 4.2.2 on 2024-12-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_roomimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
