# Generated by Django 4.2.17 on 2024-12-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_delete_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
    ]
