# Generated by Django 4.2.17 on 2024-12-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_room_category_remove_room_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app1.roomcategory'),
            preserve_default=False,
        ),
    ]
