# Generated by Django 4.2.17 on 2024-12-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_roomcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
