# Generated by Django 4.2.2 on 2024-12-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='destination_background',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='background_image',
            field=models.ImageField(default=2, upload_to='testimonials/backgrounds/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
