# Generated by Django 4.2.2 on 2024-12-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
