# Generated by Django 4.2.2 on 2024-12-31 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rename_submitted_at_contact_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
